export const ministries = [
  { number: '01', name: 'Education', text: 'Learn the Gospel, teach it to our community, and put it into hearts, homes, and hands.', items: 'Weekly sermons · YouTube teaching · Eldership Academy' },
  { number: '02', name: 'Wellness', text: 'Practice good stewardship of body and mind through nutrition, counseling, and care.', items: 'Insight Counseling · Nutritional Counseling · Edith Schaeffer Gardens' },
  { number: '03', name: 'Arts', text: 'Mirror the creativity of God through practiced, generous creative expression.', items: 'ABFid · Open Studio · Feast with Ravens · Mite Records' },
  { number: '04', name: 'Community', text: 'Gather in ways that make us meaningful participants in the nature of the Trinity.', items: 'Haven · Developmental Cadre · Volunteer Days · ABF Events' },
]

export const sundays = [
  { week: 'Week 1', title: 'Streamed Sermons', text: 'Foundational teaching for the month, recorded at our ministry campus.', note: 'Sermon dates are announced separately; public attendance is not available at this time.', image: 'streamed-sermons' },
  { week: 'Week 2', title: 'House Church', text: 'Intimate worship held in congregation homes throughout the region.', image: 'house-church' },
  { week: 'Weeks 3–4', title: 'Outreach & Witness', text: 'Active pastoral interaction, public Bible study, and on-the-spot counseling.', image: 'outreach-witness' },
  { week: 'Week 5', title: 'Synergy Sunday', text: 'Visiting other churches to worship together and create meaningful connection.' },
]

export const beliefs = [
  { title: 'Jesus Christ', short: 'In his manifestation, Jesus is both fully human and fully God.', full: ['(a). In His manifestation, Jesus is both fully human and fully God.'] },
  { title: 'The Trinity', short: 'God presents himself as Father, Son, and Holy Spirit—three unique identities in one sovereign essence.', full: ['(a). God presents Himself to humanity through Trinitarian concepts, most specifically as the Father, the Son, and the Holy Spirit – essentially harmonious in a polity of three unique identities, creating and sustaining one sovereign essence.'] },
  { title: 'Baptism', short: 'Baptism by immersion is a necessary event in our spiritual life and a key point in spiritual health.', full: ['(a). Baptism by immersion, though not necessary for salvation, is a necessary event in our spiritual life and is a key point in our spiritual health.'] },
  { title: 'The Bible', short: 'The Holy Scriptures are divinely inspired, trustworthy, and sufficient to bring us to a saving knowledge of Jesus Christ.', full: ['(a). The Holy Scriptures, as revealed in the original literary form, are self-evident, self-sustaining, sovereign, and divinely inspired. They are infallible.', 'The tradition of Scriptural transmission over time is infallible in its presentation of the original intended meaning of Scripture when: the action of canonization, translation and transmission of Scripture, including the various translations into varying languages and vernacular, contain the entirety of God’s revelation if these actions have been discerned by God’s people and maintained by the community of the Invisible Church over time and measured against previous revelation.', 'All that is contained within this tradition is complete for the accurate transmission of God’s revelation and fully able to bring a person to a saving knowledge of Jesus Christ, metamorphosis in his Spirit and sanctifying work before the Father. All other sources for defining Truth must agree with the Holy Scriptures.'] },
  { title: 'Sin and the state of man', short: 'Humanity’s focus on sin is answered by God’s grace, and salvation restores what sin has touched through the work of Christ.', full: ['(a). “Sin” is defined as “missing the mark” of God’s standard. Though God recognizes that mankind sins, His actions and intent are not subject to or in reaction to mankind’s focus on sin. The actuation of God’s outworking of His design toward mankind’s focus on sin, is in relation to mankind’s focus, not God’s standard. God’s action toward mankind, though it addresses sin, is solely for the benefit of God’s creation, and not in any way an opposition of sin, which is inconsequential to God’s sovereignty, intent for proper economy, standard for divine justice, and the outworking of God’s love toward His creation. God’s focus is not on sin, but rather on grace and the productive outworking of His economy. When mankind focused on guilt, through sin by the Law, God provided Christ in order to properly align mankind’s focus away from the guilt of sin and the Law toward the productive outworking of His economy through grace by faith.', '(b.) Salvation is necessary because, after Eden, humans are inherently sinners, in rebellion against God and in league with Satan. This is inescapable by any merit of human work or intention. The effects and outcome of sin, on the lives of humankind is absolutely pervasive, extending to all aspects of the personhood of humans. This includes relationship with God and other humans, physical actions, inner thoughts and emotional wellness.', 'Salvation is a state of Grace under which all things touched by our sin are both disconnected from their ultimate end in hellfire and actively maintained or sanctified into being an accurate display of God’s intended glory. We acknowledge that we have not been given the full understanding of the mechanics of how this works. However, It is a holistic truth of those who are adopted into it by the movement of the Holy Spirit and the work of Christ in his humanity.', 'To have Salvation, a human must receive the call of the Holy Spirit, repent of their sin and believe in the personhood and work of Christ as defined in the Holy Scriptures.'] },
  { title: 'Salvation', short: 'Salvation is not attained; it is the unmerited gift of God, provided through the work of Jesus Christ alone.', full: ['(a.) Salvation is not attained; rather, it is an unmerited gift from God.', '(b). The gift of Salvation was provided by the work of Jesus Christ alone, a carpenter from Nazareth, who was born of a virgin, Mary, raised among humans, died a criminal’s death on a cross, and defeated Death by rising from His sealed tomb three days after His death. There is no other path to Salvation but through Christ.'] },
]

export const staff = {
  Pastors: [
    { name: 'Adam Kunkel', role: 'Children’s ministries · Properties', meta: 'Husband of 10+ years · Father of 2 · Carpenter', image: 'adam', email: 'adamkunkel@abfpdx.org', playlist: 'PL5Iolp8FyArTWxHOk8f7YbAkJ7iF6C_IZ', bio: `Adam Kunkel is an Attending Elder at ABF since 2019. His ministerial responsibilities include Preaching, Teaching, Internal Ministry for the 12 and under age group, maintaining properties and leading the Culture In Sanity Podcast. Him and his wife, Brittany, have a son and daughter, Oliver and Hannah.` },
    { name: 'Josh McGary', role: 'Senior pastor · Teaching · Counseling', meta: 'Husband of 15+ years · Father of 4 · Artist · Teaching · Counseling · Bodylife', image: 'josh', email: 'joshmcgary@abfpdx.org', website: 'https://joshmcgary.com/', spotify: 'https://open.spotify.com/playlist/47UjTkYU9j6zWnYKfaVG4w', playlist: 'PL5Iolp8FyArQ8kmEZMSJfm9IHV9CG6Z0E', bio: `Josh McGary is a Custodial and Attending Elder at ABF. He is the church’s Senior Pastor. He has been a pastor at ABF since 2004. His ministerial responsibilities include Preaching, Teaching, Counseling and developing resources for the church as well as External Ministries and the Christian Resource Cooperative. He and his wife, Mashayla, have two sons and two daughters, Sophia, Joseph, Olivea & Daniel.` },
    { name: 'James Pierzina', role: 'Senior ministries · Teaching · Assets', meta: 'Husband of 25+ years · Father of 3 · Technical specialist', image: 'james', email: 'jamespierzina@abfpdx.org', playlist: 'PL5Iolp8FyArShfD_2z5u7BeRh7l7NFi83', bio: `James Pierzina is a Custodial and Attending Elder at ABF. He has been a pastor at ABF since 2004. His ministerial responsibilities include Preaching, Teaching, Counseling, Internal Ministries for congregants 50 and older and maintaining the assets of the church. Him and his wife, Julia, have a son and two daughters, Jeremiah, Jacquline, and Jasmin.` },
    { name: 'Colin Sakewitz', role: 'Youth ministries · Records and assets', meta: 'Husband of 10+ years · Father of 3 · Electrician', image: 'colin', email: 'colinsakewitz@abfpdx.org', playlist: 'PL5Iolp8FyArQXmCGt3iKUY1cCvnQwMes-', bio: `Colin Sakewitz is an Attending Elder at ABF since 2019. His ministerial responsibilities include preaching, teaching, assets, and internal ministry of the 13-25 age group, he is the Elder in charge of The Outsiders, ABF’s youth culture resource and leads the Emberwatch program. Him and his wife, Bethany, have two sons, Milo, Evan and Caleb.` },
    { name: 'Rev. Monte McGary', role: 'Elder emeritus · Teaching', meta: 'Husband of 40+ years · Father of 3 · Veteran · Professor', image: 'monte', email: 'montemcgary@abfpdx.org', playlist: 'PL5Iolp8FyArRI2tVZsPWWgvtDpi9-9cB-', bio: `Reverend Monte McGary is a current Elder Emeritus at ABF having served 10 years as its Senior Pastor and 10 years prior at Glencoe Baptist Church. He is also a retired agent of the IRS, having served with them for 28 years. He currently teaches varied business courses as an adjunct professor at Warner Pacific University, his alma mater, where he received his degrees in Religion/Social Science, BA and a Master of Religion, MREL. He also has education in Sociology and in Theology specializing in cults and the occult. Though he is retired from the Eldership of the church, he can still be seen frequently at important events, giving the occasional sermon and hosting the ABF Studios Originals: Truth Time with Pastor Monte. He and his wife, Rose, have two sons, Monte II and (ABF Senior Elder) Josh, as well as a daughter, Maraia.` },
  ],
  Deacons: [
    { name: 'Justine Braks', role: 'Counseling', meta: 'Wife · Mother of 2', image: 'justine', email: 'justinebraks@abfpdx.org', bio: `Justine Braks is an Attending Deacon of ABF. She is the Deacon of Counseling. Her ministerial responsibilities include administration of the church’s counseling program, counseling in the Insight Program and maintaining the spiritual safety and development of resources for the children of ABF. She is also a co-host of Nite Lite Radio, the church’s podcast on mental health and counsel. She is married to Paul Braks and has two kids, Elizabeth and Ethan.` },
    { name: 'Brittany Kunkel', role: 'Optics and legacy', meta: 'Wife · Mother of 2 · Bible study', image: 'britt', email: 'brittanykunkel@abfpdx.org', bio: `Brittany Kunkel is an Attending Deacon. She is the Director of Optics and Legacy for ABF. She heads ABF’s Project Vigilance. She is a leader in Outsiders, ABF’s youth culture resource, and she teaches the Cadre Jr class in the Developmental Cadre program. She is married to Elder Adam Kunkel and has a son and a daughter, Oliver and Hannah.` },
    { name: 'Jon Parker', role: 'Finances and assets', meta: 'Husband of 15+ years · Father of 2', image: 'jon', email: 'jonparker@abfpdx.org', bio: `Jon Parker is an Attending Deacon of ABF. His ministerial responsibilities are assisting in maintaining the Assets of the church. He is married to Deacon Heidi Parker, they have a son and daughter, Aidan and Madilyn.` },
    { name: 'Heidi Parker', role: 'External ministry', meta: 'Wife of 15+ years · Mother of 2 · Manager', image: 'heidi', bio: `Heidi Parker is an Attending Deacon of ABF. She is the Director of External Ministry. Her ministerial responsibilities include teaching, networking, developing resources for the congregation, public and other churches and maintaining the general external mindshare and welfare of the church. She is married to Deacon Jon Parker, and they have a son and daughter, Aidan and Madilyn.` },
    { name: 'Mashayla McGary', role: 'Internal ministry', meta: 'Wife of 15+ years · Mother of 4 · Nutritionist', image: 'mashayla', email: 'mashaylamcgary@abfpdx.org', bio: `Mashayla McGary is an Attending Deacon of ABF. She is the Director of Internal Ministry. Her ministerial responsibilities include teaching, counseling, developing resources for the congregation and maintaining the general welfare of the church. She is married to Elder Josh McGary. They have a son and two daughters, Joseph, Sophia, Olivia and Daniel.` },
    { name: 'Kelsey Salazar', role: 'Internal and youth ministries', meta: 'Child-care specialist · Volunteer coordinator', image: 'kelsey', email: 'kelseysalazar@abfpdx.org', bio: `Kelsey Salazar is a Deacon for the office of Internal Ministry. Her ministerial responsibilities include the coordination of the churches multiple calendars, events and meetings. She is a leader in Outsiders, ABF’s youth culture resource, and ABF’s volunteer coordinator.` },
  ],
  'Interns & Staff': [
    { name: 'Jasmin Pierzina', role: 'Optics and legacy', meta: 'Artist · Designer', image: 'jasmin', email: 'jasminpierzina@abfpdx.org', bio: `Jasmin Pierzina is an intern for the office of Optics. Her ministerial responsibilities include heading up the design department of ABF’s Project Vigilance, and ABFid, the church’s design studio.` },
    { name: 'Bethany Sakewitz', role: 'External ministry', meta: 'Wife · Mother of 3 · Manager', image: 'beth', email: 'bethanysakewitz@abfpdx.org', bio: `Bethany Sakewitz is an intern for the office of External Ministry. Her ministerial responsibilities include working for ABF’s Upreach Program and Christian Resource Cooperative. She is married to Elder Colin Sakewitz and has three sons, Milo, Evan and Caleb.` },
    { name: 'Jacob Browning', role: 'Counseling', meta: 'Husband · Veteran · Chaplain in training', image: 'jacob', email: 'jacobbrowning@abfpdx.org', bio: `Jacob Browning is a member of the Haven ministry. He is a Chaplain in training and a Pastor in training in the Eldership Academy. He is married to Jennifer Browning.` },
    { name: 'Jennifer Browning', role: 'Children’s ministries', meta: 'Wife · Child-care specialist', image: 'jenn', email: 'jenniferbrowning@abfpdx.org', bio: `Jennifer Browning is a teacher for ABF’s Developmental Cadre Program. She is responsible to help parents of toddler aged children and advocate for their children’s education in the Cadre Tots program. She is married to Jacob Browning.` },
    { name: 'Jacquline Pierzina', role: 'Youth ministry', meta: 'Customer-service specialist · Chaplain in training', image: 'jacquline', email: 'jacqulinepierzina@abfpdx.org', bio: `Jacquline Pierzina is a leader in the Outsiders Ministry. She is also a leader of the Baby Ruth’s Society and a Chaplain in training in the Insight Program.` },
  ],
}
